export const COM_SHOW_SIDE_BAR = 'COM_SHOW_SIDE_BAR' // 侧边栏
export const COM_SAVE_SEARCH_HISTORY = 'COM_SAVE_SEARCH_HISTORY'
export const COM_DELETE_SEARCH_HISTORY = 'COM_DELETE_SEARCH_HISTORY'
export const COM_CLEAR_SEARCH_HISTORY = 'COM_CLEAR_SEARCH_HISTORY'// 清除所有历史